### ISSUE TITLE
Android - plugin 1.2.0.0 and 3 dimensions build

### ISSUE THREAD

**Issue by santanaluiz** [mannodermaus/android-junit5#110]
Hi,

I have a build with multiple dimensions and I'm having problems to add JUnit 5 (with AS 3.3 canary).
I've followed [this wiki page](https://github.com/mannodermaus/android-junit5/wiki/Migrating-from-1.0.x)

Problem is, it can not find extension and I don't see how to solve this:

```
Gradle sync failed: Extension with name 'appDevelopmentFilters' does not exist. Currently registered extension names: [ext, filters, debugFilters, releaseFilters, appFilters, localFilters, developmentFilters, productionFilters, ciFilters, appDevelopmentDebugFilters, appDevelopmentReleaseFilters, appDevelopmentCiFilters, appProductionDebugFilters, appProductionReleaseFilters, appProductionCiFilters, appLocalDebugFilters, appLocalReleaseFilters, appLocalCiFilters]
```

**Comment by mannodermaus** [comment]
Could you share the excerpt from your `build.gradle` file in which you define the `productFlavors` and their dimensions? Seems like there might be a hole where not all variants get their extensions configured properly. As a quick workaround, you can copy your `appDevelopmentFilters` block three times, one time for each of these variants: `appDevelopmentDebugFilters, appDevelopmentReleaseFilters, appDevelopmentCiFilters`

**Comment by santanaluiz** [comment]
so you can substitue brandA (or brandB) with app

In this case tasks would look like
`brandADevelopmentDebugFilters`

**Comment by pawel-prochniak** [comment]
I have exactly the same problem. 
I don't add any filter blocks to my build.gradle.
Basing on @santanaluiz build.gradle example, it looks like plugin expects for instance:

> brandAFilters
> developmentFilters

whereas it should detect:
>brandADevelopmentFilters

**Comment by santanaluiz** [comment]
@mannodermaus could you be more specific on how to copy the filter as workaround?

**Comment by mannodermaus** [comment]
A fix has been merged to master, and will be included in the next release. If you could, please check if the latest `1.2.0.1-SNAPSHOT` indeed fixes the problem for you!

**Comment by ebrowne72** [comment]
Any idea when 1.2.0.1 will be released?

**Comment by mannodermaus** [comment]
I was hoping to get some clarification on the snapshot, because the applied change works at least for me. I was aiming for the second half of this week for the bugfix release!
