### ISSUE TITLE
Parameterized Tests create "null" test that doesn't finish

### ISSUE THREAD

**Issue by tommyalatalo** [mannodermaus/android-junit5#114]
When writing parameterized tests, using strings in my case I get an extra test which is called "null", I'm using this with Android and Android Studio.

Example:

```
@DisplayName("Parameterized Test")
    @ParameterizedTest(name = "Test with [{arguments}]")
    @ValueSource(strings = {"FIRST","SECOND"})
    public void paramTest(String testStr) {
assertThat(True).isTrue()
}
```

The expected output would be:
Parameterized Test
|--[Test with [FIRST]
|--[Test with [SECOND]

Actual result:
Parameterized Test
|-- null
|--[Test with [FIRST]
|--[Test with [SECOND]

The null test never finishes and the overall test task is terminated.

**Comment by mannodermaus** [comment]
What version of the android-junit5 plugin, as well as JUnit 5 itself, are you pulling in? Also, can you verify that this also happens in a pure-Java project? I'm not entirely sure that this is related to this plugin itself, but if reproducible, it might be interesting for the JUnit 5 team themselves.

**Comment by tommyalatalo** [comment]
> What version of the android-junit5 plugin, as well as JUnit 5 itself, are you pulling in? Also, can you verify that this also happens in a pure-Java project? I'm not entirely sure that this is related to this plugin itself, but if reproducible, it might be interesting for the JUnit 5 team themselves.

These are in my gradle file when running into the above issue:
androidTestImplementation 'junit:junit:4.12'
androidTestImplementation 'org.junit.jupiter:junit-jupiter-params:5.3.1'
androidTestImplementation 'org.junit.jupiter:junit-jupiter-api:5.3.1'
androidTestImplementation 'de.mannodermaus.junit5:android-instrumentation-test:0.2.2'
androidTestImplementation 'org.assertj:assertj-core:3.11.1'
androidTestImplementation 'org.mockito:mockito-android:2.6.3'

**Comment by mannodermaus** [comment]
This will be addressed in the upcoming release of the instrumentation test libraries. If you want to check it today, please make sure to use the new artifacts, and use the `1.2.0-SNAPSHOT` for the time being. You can also check #185, a very similar issue, for more information. [Here's a guide on how to get the setup done.](https://github.com/mannodermaus/android-junit5/wiki/Instrumentation-Tests-Setup)
