### ISSUE TITLE
Check compatibility with Gradle 5

### ISSUE THREAD

**Issue by mannodermaus** [mannodermaus/android-junit5#118]
https://docs.gradle.org/5.0-milestone-1/release-notes.html

**Comment by mannodermaus** [comment]
The unit tests for the plugin itself seem to work with Gradle 5, however this ticket will have to be postponed until the Android Gradle Plugin supports the new version as well:

```
Unsupported method: IdeaModuleDependency.getDependencyModule().
The version of Gradle you connect to does not support that method.
To resolve the problem you can change/upgrade the target version of Gradle you connect to.
Alternatively, you can ignore this exception and read other information from the model.
```

**Comment by autonomousapps** [comment]
Could you be more specific about what you're trying to do? I was unaware of any incompatibilities between AGP and Gradle 5.0. (I work for Gradle)

**Comment by mannodermaus** [comment]
Apologies, I was inferring a problem with the AGP from the above error message. The plugin doesn't use that specific method anywhere in its code, and after removing all of the Android modules from the project, the Gradle Sync works again. That's why I concluded that support was lacking on their end.

On a greenfield Android project using Android Studio 3.2.1, it looks like the daemon gets stuck at `Build model 'org.jetbrains.plugins.gradle.model.BuildScriptClasspathModel' for root project`. After I manage to get it unstuck, I'll try to investigate which piece of code triggers that unsupported API in the android-junit5 project.

**Comment by autonomousapps** [comment]
No apologies needed. I'd just like to be of service in helping you make this compatible with Gradle 5, assuming that Gradle 5 is actually compatible with the current stable Android plugin (which I thought it was). I look forward to hearing what you figure out from your investigations.

**Comment by mannodermaus** [comment]
Using Android Studio 3.3, the daemon doesn't get stuck, so I suppose it's something to do with the internally used version of IntelliJ or something. The same seems to be the case for that other error - on the greenfield project in AS 3.3, no problems arise with either Gradle 5 nor the android-junit5. Everything seems to work just fine! Nice.

**Comment by mannodermaus** [comment]
FYI, looks like the issue regarding `IdeaModuleDependency` mentioned above also happened on one of the AS 3.4 Canary versions, and it's filed [here](https://issuetracker.google.com/issues/119209468).
