### ISSUE TITLE
Using different JaCoCo version

### ISSUE THREAD

**Issue by ebrowne72** [mannodermaus/android-junit5#122]
I need to use an older version of JaCoCo (0.7.9) in my builds. Can you add a "toolVersion" option to jacocoOptions?

**Comment by mannodermaus** [comment]
The JUnit 5 plugin doesn't bundle Jacoco in on its own - it merely creates companion tasks once the presence of the `jacoco` plugin is detected. You should be able to use a different version through the Jacoco DSL itself:

```
jacoco {
    toolVersion = "0.7.9"
}
```

**Comment by ebrowne72** [comment]
Ah, that worked.
