### ISSUE TITLE
Support for Android Projects without `testDebugUnitTest` task

### ISSUE THREAD

**Issue by matejdro** [mannodermaus/android-junit5#125]
Currently plugin seems to assume that every android project has `testDebugUnitTest` and gradle configure will fail if there isn't one.

But that is not guaranteed. For example, module can be of type `com.android.test` which is a module contianing only instrumented tests ([Example](https://github.com/googlesamples/android-testing-templates/tree/master/AndroidTestingBlueprint/module-flavor1-androidTest-only))

Workaround for the issue is to add this to the failing module's `build.gradle`:

`task testDebugUnitTest(type : com.android.build.gradle.tasks.factory.AndroidUnitTest)`

**Comment by mannodermaus** [comment]
Interesting - I wasn't aware that `test_UnitTest` tasks are not a ubiquitous thing throughout all Android plugins. Will look into this, especially since `com.android.test` [is among the supported plugins](https://github.com/mannodermaus/android-junit5/blob/master/android-junit5/src/main/kotlin/de/mannodermaus/gradle/plugins/junit5/Configuration.kt#L48).

**Comment by mannodermaus** [comment]
After reviewing the options here, I'm considering to simply disable JUnit 5 processing for modules that apply `com.android.test`. There are no unit test tasks to configure anyways, so the plugin wouldn't have a purpose here. The integration of instrumentation tests is unaffected by this, so you could still use the JUnit 5 instrumentation test libraries without applying `android-junit5`. Does this sound reasonable to you?

**Comment by matejdro** [comment]
Yes. I assume instrumented tests would still work as JUnit5?

**Comment by mannodermaus** [comment]
Yeah, for those you'd need some distinct setup through libraries, but the Gradle tasks themselves would reamin untouched.

**Comment by mannodermaus** [comment]
The recently released `1.3.2.0` removed support for the `com.android.test` plugin, so it won't try to configure non-existent unit test tasks anymore.
