### ISSUE TITLE
Mention upstream AGP issue

### ISSUE THREAD

**Issue by ming13** [mannodermaus/android-junit5#129]
Up to this point I haven’t even tried to run JUnit 5-based unit tests in Android projects. Am I understanding correctly that it is not quite possible at this point? Is there an upstream AGP issue we can star and track? I was searching for it across Android issue tracker with little success.

**Comment by autonomousapps** [comment]
? The whole point of this project is to enable the use of junit5 unit tests in an android project. Rest assured, it works just fine.

I asked Google about this once a year or more ago, and it was not on their radar to add native support. Remember how long it took them to even give us junit4 support!

**Comment by ming13** [comment]
Well, the more community can push it upstream, the better. Still — is there an upstream issue or it should be created?

**Comment by mannodermaus** [comment]
I think that having an upstream issue to heighten the visibility of this feature request would be useful. I personally haven't filed any such issue - the only issue tangentially related to JUnit 5 was about `module-info.class` exclusion in newer versions of the framework. @ming13, I'd be happy to include the issue link in the README if you'd like to open it upstream.

**Comment by matejdro** [comment]
I could not find existing ticket, so I have created one here: https://issuetracker.google.com/issues/127100532

Not that I think that anything would change but one can cream.

**Comment by autonomousapps** [comment]
FYI, I raised this in a related issue a while ago. Here's the link: https://issuetracker.google.com/u/2/issues/79189568

**Comment by matejdro** [comment]
It looks like Google is now migrating everything test-related to their Github page. I have also created issue here: https://github.com/android/android-test/issues/224

**Comment by mannodermaus** [comment]
Thanks, everybody! I'll aggregate these links into a new section in the Readme.
