### ISSUE TITLE
Android Test Orchestrator support

### ISSUE THREAD

**Issue by zawadz88** [mannodermaus/android-junit5#163]
Hi,
I've tried running tests with Android Test Orchestrator, however it seems to be broken now (it works without Orchestrator though).
My code: https://github.com/zawadz88/ExoPlayerAudioSample/commit/61257d3fc9f8edd57a8d40eed4ee7ccbc7b8fa7d

I've added two tests in a single class like this:
```
package com.github.zawadz88.exoplayeraudiosample.test
// imports
class MainActivityTest {

    @Suppress("unused")
    @JvmField
    @RegisterExtension
    val scenarioExtension = ActivityScenarioExtension.launch<MainActivity>()

    @Test
    fun play_button_should_be_displayed() {
        // some test
    }

    @Test
    fun prev_and_next_buttons_should_be_disabled() {
        // some other test
    }
}
```
When I setup Android Test Orchestrator and run the tests, `AndroidJUnitRunner` finds the tests on first run but creates an invalid Test description which makes it impossible to run them.

An expected test execution here would be:
1. We run the tests from command-line/Android Studio
2. On first test execution `AndroidJUnitRunner` collects a test list. In my case this should add two tests - `com.github.zawadz88.exoplayeraudiosample.test.MainActivityTest#play_button_should_be_displayed` and `com.github.zawadz88.exoplayeraudiosample.test.MainActivityTest#prev_and_next_buttons_should_be_disabled`
3. Actual tests should be passed as test arguments to `AndroidJUnitRunner`  under a `class` key.

What actually happens is that in 2. `MainActivityTest#play_button_should_be_displayed()` and `MainActivityTest#prev_and_next_buttons_should_be_disabled( )` get passed to Orchestrator and in 3. they are not found which causes the instrumentation to fail.

`AndroidJUnitRunner` code responsible for collecting tests:
<img width="685" alt="Screen Shot 2019-04-08 at 21 49 18" src="https://user-images.githubusercontent.com/3322260/55752459-616a1c80-5a48-11e9-95da-174af1a300e8.png">
<img width="543" alt="Screen Shot 2019-04-08 at 21 49 32" src="https://user-images.githubusercontent.com/3322260/55752460-616a1c80-5a48-11e9-8ecc-38462d82c610.png">

I can see two ways to potentially fix it:
1. `de.mannodermaus.junit5.AndroidJUnit5` could override `getDescription` and create something compliant with Test Orchestrator.
2. Create a custom `AndroidJUnitRunner` which would convert JUnit5 created class arguments to real tests (I've done something similar in https://github.com/stepstone-tech/AndroidTestXRunner/blob/master/xrunner-library/src/main/java/com/stepstone/xrunner/AndroidJUnitXRunner.kt). This has two downsides though... 1 - it's super hacky and requires reflection, 2 - converting simple class names to full names is problematic and it means there should be no tests with the same name.

Please let me know what you think about it and if Android Test Orchestrator support is planned :)

**Comment by zawadz88** [comment]
I dug a bit into JUnit5's source code and upon inspecting `JUnitPlatform ` I found the class responsible for creating `Description`s: https://github.com/junit-team/junit5/blob/master/junit-platform-runner/src/main/java/org/junit/platform/runner/JUnitPlatformTestTree.java

Now, if I annotate my `MainActivityTest` with `@UseTechnicalNames` this is working :) One caveat is that `junit-platform-runner` cannot be a `androidTestRuntimeOnly` dependency - it needs to be `androidTestImplementation` (maybe somewhat related to #161) for the annotation to be available when compiling.

**Comment by zawadz88** [comment]
There is one more drawback here... 
Adding `androidTestImplementation "org.junit.platform:junit-platform-runner:1.4.2"` as I mentioned above would actually make your JUnit5 unit tests fail in Android Studio with the following:
```
java.lang.NoClassDefFoundError: org/junit/platform/launcher/TestExecutionListener
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.intellij.junit5.JUnit5IdeaTestRunner.createListeners(JUnit5IdeaTestRunner.java:39)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:45)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.ClassNotFoundException: org.junit.platform.launcher.TestExecutionListener
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 16 more
```
It's working fine from the command line however in Android Studio you need to comment this line out.
Happens with Android Studio 3.3 and 3.4 RC3 and latest Android Gradle Plugins for these versions.

**Comment by mannodermaus** [comment]
Thanks for the information! I have never used Android Test Orchestrator myself, so it's great insight to look behind the scenes of how it works.

Let me verify that I understood the problem correctly: The Test Orchestrator requires fully qualified method names, but JUnit 5 cuts off the package from the name? Therefore, you have to annotate your test class with `@UseTechnicalNames`, since that will cause the runner to use the FQCN instead of the display name.

The requirement of the platform runner being a `runtimeOnly` dependency was established when it would otherwise interfere with compilation, and also execution on old API levels. That's why the platform runner is not exposed at compile time. The positive: `@UseTechnicalNames` actually comes from another artifact, `junit-platform-suite-api`! You should be able to use that instead and have it work the same.

I wish we had a say in how `JUnitPlatformTestTree` generates its descriptions, outside of that annotation. For now, it looks like it's going to be a requirement to add the annotation if you want to use the Test Orchestrator. Otherwise, we could either reimplement `JUnitPlatform`, or hack our changes into it, neither of which I'm completely stoked about at this point.

**Comment by zawadz88** [comment]
Yes, that's exactly the issue. I'll check with `junit-platform-suite-api` and post back here.
Thanks for replying!
P.S. if you're interested about the Orchestrator you might check out this article: https://medium.com/stepstone-tech/android-test-orchestrator-unmasked-83b8879928fa it's basically what I described here but in more detail

**Comment by zawadz88** [comment]
`androidTestImplementation "org.junit.platform:junit-platform-suite-api:1.4.2"` did the trick i.e. it works with instrumentation tests and makes unit tests pass in Android Studio as well.

I think it would be nice to have some info on that in the wiki and/or README so people don't report this back as an issue :)

**Comment by mannodermaus** [comment]
I'm definitely going to add a section to the Wiki & the README file. I hope that we'll find a solution that makes the Orchestrator work more transparently in the future, but for now, this is good enough. Thanks again for the research!
