### ISSUE TITLE
Out of memory running unit tests

### ISSUE THREAD

**Issue by ebrowne72** [mannodermaus/android-junit5#165]
Updated to:
* Android Gradle plugin 3.4.0
* Gradle 5.1.1
* Android JUnit 5 plugin 1.4.2.0
* JUnit 5.4.2

I've got about 4500 tests, and when I run them from the command line I run out of memory. I ripped out about 1000 tests and it was able to run, but very slow -- AS 3.4 runs the tests in ~50s, while the command line took 2:28.

**Comment by mannodermaus** [comment]
I'm not certain about this plugin's relevance to the memory impact of Gradle. Are you saying that, compared to using an older version of the plugin, the latest environment requires more resources? The plugin's main purpose is to configure the test tasks, and if you run out of memory during their execution, this is beyond the scope of the plugin directly - unless we can show that your tests execute just fine after disabling the plugin.

**Comment by ebrowne72** [comment]
Any suggestion on how I can debug what's using so much memory so I can file a bug with the offending project?

**Comment by autonomousapps** [comment]
@ebrowne72 use [gradle-profiler](https://github.com/gradle/gradle-profiler) with your favorite profiler (we prefer async-profiler), then inspect the resultant flamegraph.

And/or consider tweaking your jvmargs. E.g.,
```
# gradle.properties
org.gradle.jvmargs=-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
```
With `-XX:+HeapDumpOnOutOfMemoryError`, you should also get an hprof file you can inspect with your favorite tool.

**Comment by mannodermaus** [comment]
Thanks for the insight, @autonomousapps! @ebrowne72, please feel free to reopen this if you can spot something shady with the memory management of this plugin! Closing this in the meantime. 🙇

**Comment by ebrowne72** [comment]
If anyone is curious, after a few months I merged a bunch of commits in from another branch, and the memory issues were fixed. I have no idea what I changed that fixed it.
