### ISSUE TITLE
Does this plugin work with Gradle Plugin DSL?

### ISSUE THREAD

**Issue by Lingviston** [mannodermaus/android-junit5#166]
I'm trying to enable it like this in my root build.gradle file:

```
plugins {

    id "de.mannodermaus.android-junit5" version "1.4.2.0"
}
```

In my settings.gradle I have the following:
```
pluginManagement {

    repositories {

        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
```

However whenever I try to sync I receive the following error:

> Plugin [id: 'de.mannodermaus.android-junit5', version: '1.4.2.0'] was not found in any of the following sources:
> 
> - Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
> - Plugin Repositories (could not resolve plugin artifact 'de.mannodermaus.android-junit5:de.mannodermaus.android-junit5.gradle.plugin:1.4.2.0')
>   Searched in the following repositories:
>     Google
>     MavenRepo
>     Gradle Central Plugin Repository

So, can I use it together with new Plugins DSL?

**Comment by mannodermaus** [comment]
This plugin doesn't expose the necessary plugin marker artifact required by the Plugins DSL. You'd need a custom resolution strategy to map to the correct coordinates in your `pluginManagement` block:

```groovy
pluginManagement {
    repositories {
        mavenCentral()
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == "de.mannodermaus.android-junit5") {
                useModule("de.mannodermaus.gradle.plugins:android-junit5:$requested.version")
            }
        }
    }
}
```

The Android Gradle Plugin also doesn't support the Plugins DSL, as far as I'm aware. Do you resolve that plugin similarly?

**Comment by autonomousapps** [comment]
I use the plugins DSL for Android apps and libraries. You can do what you
suggested, but it's also sufficient to add the plugin to the buildscript
dependency classpath, like normal. In fact, I'm sure that's what I already
do for THIS plugin.

**Comment by mannodermaus** [comment]
I quickly verified @autonomousapps' statement and this actually works as well, although you need to strip away the version off the line inside the `plugins` block.

@Lingviston, as an alternative to the workaround mentioned above, this works as well:

```groovy
// Project-level build.gradle:
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "de.mannodermaus.gradle.plugins:android-junit5:1.4.2.0"
    }
}

// Module-level build.gradle:
plugins {
    id "de.mannodermaus.android-junit5"
}
```

Either of these approaches should work fine for your use case.

**Comment by autonomousapps** [comment]
Yes, exactly! Sorry I didn't mention that. On my phone.

**Comment by Lingviston** [comment]
@mannodermaus yeah, the old approach with declaration in builscript works, but new plugin DSL claimed to be more effective in terms of build performance.

**Comment by Legion2** [comment]
I think to be able to use the plugins DSL syntax without the buildscript block this plugin must be published to the [Gradle plugin portal](https://plugins.gradle.org/).
