### ISSUE TITLE
Regression: UnitTestOptions are no longer evaluated

### ISSUE THREAD

**Issue by frapontillo** [mannodermaus/android-junit5#169]
The support for `returnDefaultValues` and `includeAndroidResources` added in #80 is no longer present in the plugin.

Has this been done purposefully? If so, is there any way to enable those flags for JUnit 4 and JUnit 5 in the same project?

**Comment by mannodermaus** [comment]
After a certain point, there was no need for the duplicated DSL in the plugin anymore. A couple of versions ago, when this plugin raised the minimum required Gradle version, it stopped creating its own test tasks (it used to rely on `JavaExec` tasks and a lot of classpath trickery), and instead started to configure the default test tasks exposed by the Android Gradle Plugin to support the JUnit Platform. Because of that, you would use now the existing `testOptions` DSL to configure default values & Android resources, just like you would in a purely-JUnit4 environment.

**Comment by frapontillo** [comment]
I have tried using the standard DSL, but for some reason the `returnDefaultValues` is ignored for both JUnit 4 and JUnit 5 tests. I created a sample project at https://github.com/frapontillo/android-junit-4-5-demo. As you can see in `build.gradle` I have declared:

```gradle
testOptions {
    unitTests {
        returnDefaultValues = true
        includeAndroidResources = true
    }
}
```

**Comment by mannodermaus** [comment]
Thanks for the sample project. In my environment, `returnDefaultValues` works as intended. When it's off, both tests throw an exception upon use of the Intent class:
```
java.lang.RuntimeException: Method putExtra in android.content.Intent not mocked. See http://g.co/androidstudio/not-mocked for details.
```

When it's on, the mocked `android.jar` is used, which makes all Android APIs return the default value. This is `null` for Object-based APIs like `Intent#putExtra`, and makes both assertions fail as expected:
```
java.lang.AssertionError
        (...)
	at org.junit.Assert.assertNotNull(Assert.java:712)
```

Using this setting won't magically allow the Android SDK to be usable to the fullest extent during tests, it's simply a compatibility mode. If you really wanted to put some extras into an Intent on the JVM, you'd need to use something like Robolectric.

**Comment by frapontillo** [comment]
You are totally right, I just noticed that for some reasons the demo project is able to run. I am indeed getting in a weird situation where, if I enable those `unitTests` options, I only get JUnit 5, Spek 1 and Spek 2 tests running, and not JUnit 4.
I cannot replicate it in the demo project, so it must be something else messing up my configuration.

I will update this issue when I find a solution, as it may be useful for someone else.

**Comment by frapontillo** [comment]
This was instantly fixed by updating `org.junit.vintage:junit-vintage-engine`, `org.junit.jupiter:junit-jupiter-api` and `org.junit.jupiter:junit-jupiter-engine` from `5.4.2` to `5.5.0-M1`.
