### ISSUE TITLE
Is this plugin still needed for JVM test?

### ISSUE THREAD

**Issue by emartynov** [mannodermaus/android-junit5#181]
Hey, I was triggered by slack message about some issues with junit5. I started checking our setup and found that we don't use this plugin to run tests on JVM.

So the question - is this plugin still required for JVM tests?

We are on AGP 3.4.2 and gradle 5.5.1.

**Comment by mannodermaus** [comment]
In a nutshell, the plugin basically encapsluates `Test.useJUnitPlatform()` and provides some filters & configuration for unit tests. Ergo, if you're working with a basic structure for your unit tests and don't require features such as instrumentation test support, or per-flavor filters & configuration (i.e.: you have one set of unit tests across all build types & product flavors of your app), you don't require the plugin. May I ask if these messages regarding JUnit 5 originated from this plugin? If so, I'd appreciate some details about what doesn't work for you.

**Comment by emartynov** [comment]
This is some android slack community where a conversation started about updating to AGP 3.6 and failing build. That later led to #180 issue. And I decided to ask this question since we are long-time using junit5 and we don't require your plugin to make it running.

Thank you for your answer!
