### ISSUE TITLE
Issue with latest AGP 3.6.0-alpha06

### ISSUE THREAD

**Issue by pgreze** [mannodermaus/android-junit5#183]
I was experimenting new versions of [Android Gradle Plugin](https://mvnrepository.com/artifact/com.android.tools.build/gradle?repo=google) and I faced this issue with **3.6.0-alpha06**:

```
* What went wrong:
A problem occurred configuring project ':app'.
> No such property: javaOutputDir for class: com.android.build.gradle.internal.scope.VariantScopeImpl
```

Full stacktrace: https://gist.github.com/pgreze/5dc2aa87f5b5925637072db5831cfff8

Same issue with 3.6.0-alpha05, I haven't tried with other versions.
I'm opening this issue to give you visibility on a possible future issue if next stable version of AGP is including this javaOutputDir.

**Comment by mannodermaus** [comment]
What is your android-junit5 plugin version? We stopped using `javaOutputDir` a while ago, and the latest plugin (`1.5.1.0`) works with AGP 3.6 up to the most recent release. Please upgrade your env and try again. If it still doesn't work, feel free to reopen this issue.
