### ISSUE TITLE
Cannot run individual instrumented tests

### ISSUE THREAD

**Issue by ktkopone** [mannodermaus/android-junit5#184]
Using gradle to try to run an individual instrumented test method will instead run all tests within that method's class.

E.g. running `./gradlew clean connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=stupidSampleGradleProject.StupidConnectedTest#stupidConnectedPassTest` will run all tests in the `StupidConnectedTest` class, rather than only the specified one. (See https://github.com/mannodermaus/android-junit5/issues/174 for the approximate build.gradle and sample test file configuration I'm using).

I verified that this was not an issue when running equivalent JUnit 4 instrumentation tests.

Let me know if you need more details to reproduce!

**Comment by mannodermaus** [comment]
Thanks for reporting! I'm assuming that the JUnit 5 `DiscoverySelectors` only checking for classes, not methods, will cause this to happen. I'll look into expanding support for this based on what's passed to the runner.

**Comment by mannodermaus** [comment]
This will be addressed in the upcoming release of the instrumentation test libraries. Can you try with the `1.2.0-SNAPSHOT` of `android-test-runner` (and  `android-test-core` if you use it)?

**Comment by ktkopone** [comment]
The snapshot looks good; both running single tests from console and IDE seem to work fine with running either single or multiple tests now (putting aside https://github.com/mannodermaus/android-junit5/issues/185)  Thanks!

**Comment by mannodermaus** [comment]
Thanks for confirming! I'd like to vet your other issue as well before committing to a full release, so please stay tuned for more once I get another time slot.

**Comment by mannodermaus** [comment]
Released in 1.2.0!
