### ISSUE TITLE
android-test-runner dependency cannot be added via root script

### ISSUE THREAD

**Issue by matejdro** [mannodermaus/android-junit5#188]
When using JUnit5, list of test and instrumented test dependencies is pretty long, so copy pasting them between buildscripts in various modules is tedius and duplicating.

Instead, all dependencies could be added to the root buildscript that applies them to all submodules:

```groovy
subprojects {
    afterEvaluate {
        dependencies {
             ...
             androidTestRuntimeOnly "de.mannodermaus.junit5:android-test-runner:1.0.0"
        }
    }
}
```

Unfortunately, when doing so, JUnit5 plugin will still complain about "Incomplete configuration for JUnit 5 instrumentation tests: Add the android-test-runner library to the androidTestRuntimeOnly configuration's dependencies"

`android-test-runner` dependency needs to be added in the project's build script, while other dependencies can be added via root script.

**Comment by mannodermaus** [comment]
The plugin will evaluate the configuration in `afterEvaluate` as well, and the order of execution seems to favor it over your custom block, causing the message. The integrity check is an aid for developers for exactly the reason you outlined - it's slightly tedious to set up the different components of JUnit 5 for it.

If you need to disable the plugin's integrity check, there is a [handy DSL function](https://github.com/mannodermaus/android-junit5/wiki/Instrumentation-Tests-Setup#disabling-the-automatic-check) that should do the trick for you.

**Comment by matejdro** [comment]
Wow did not know about disabling the check. Thanks!
