### ISSUE TITLE
`instrumentation` project cannot be opened on windows

### ISSUE THREAD

**Issue by matejdro** [mannodermaus/android-junit5#198]
It looks like `instrumentation` sample project uses symlinks, which are not supported on Windows.

When attempting to open the project on Windows, `build.gradle.kts` is interpreted as a text file pointing to actual location, resulting in build error:

![image](https://user-images.githubusercontent.com/507922/69813954-8be53180-11f3-11ea-8977-84c6c4791f95.png)

**Comment by mannodermaus** [comment]
The symbolic links will be replaced by a mixture of duplicated build logic & commonly shared files as soon as https://github.com/mannodermaus/android-junit5/pull/235 is merged. Going forward, you should be able to contribute to the project from a Windows environment. 🙏
