### ISSUE TITLE
No tests were found when Run Tests in folder

### ISSUE THREAD

**Issue by guuilp** [mannodermaus/android-junit5#202]
Something that I like to do before opening a Pull Request is to run all tests from the module I just modified, like in the bellow image.

![image](https://user-images.githubusercontent.com/5278328/70400428-c6c44200-1a09-11ea-89a6-35c710f779fc.png)

I have a pet project (https://github.com/guuilp/RickAndMorty) that I'm testing JUnit 5 using your gradle plugin.

Everything I tested is working except this Run Tests in a folder I mentioned. When I try to do that, I get this error:
![image](https://user-images.githubusercontent.com/5278328/70400532-1c005380-1a0a-11ea-92c8-e47d2b17bd52.png)

If you want to reproduce, just import my project (https://github.com/guuilp/RickAndMorty) and go to character module > src/test/java > right click and then `Run Tests in Java'`.

To know it's an issue with the JUnit5 gradle plugin, I checkout on `8c0e1738984106f3e5fa96e896743481e8a7b1d3` in my project (commit before adding the JUnit 5 to the project) and then tried the same option and it worked.

**Comment by ktkopone** [comment]
I believe this is a known issue that is waiting on Android Studio to pull in this fix (by this repo's author): https://github.com/JetBrains/intellij-community/pull/1152

**Comment by mannodermaus** [comment]
This problem is indeed resolved in the IDEA codebase upstream and awaiting release in a future version of Android Studio. Thanks @ktkopone for providing the link! In the meantime, we will have to rely on Gradle for the single-module test runs instead of the IDE actions.

**Comment by IgorGanapolsky** [comment]
This issue still exists in Android Studio 4.2
