### ISSUE TITLE
Doesn't work with Android Studio 4.1

### ISSUE THREAD

**Issue by roshanthejoker** [mannodermaus/android-junit5#210]
I am playing with Android Studio 4.1 with my project and had setup with the plugin to support my tests written in JUnit 5. 

When trying to sync, it crashes with error log:
`Unable to find method 'com.android.build.gradle.internal.variant.BaseVariantData.getScope()Lcom/android/build/gradle/internal/scope/VariantScope;'.`

Also I am using this setup for supporting spek:

`android {

    testOptions {

        junitPlatform {
            filters {
                engines {
                    include 'spek2' 'junit-vintage'
                }
            }
        }
        unitTests.all {
            useJUnitPlatform()
            testLogging.events = ["passed", "skipped", "failed"]
        }

    }
}
`

I don't know where to find more info about the issue.

**Comment by mannodermaus** [comment]
This is known and handled (#208) for the upcoming version of the plugin. If you want the fix now, please try with `1.6.0.1-SNAPSHOT` until then.
