### ISSUE TITLE
How can I mark a test as 'error'

### ISSUE THREAD

**Issue by Moriarty16** [mannodermaus/android-junit5#212]
I understand when to mark a test as 'pass', 'fail' or 'skip', but I'm wondering how to mark a test as 'error'.
Demo test result: 
`testsuite name="MainTest" tests="5" failures="0" errors="0" skipped="0" time="102.631"`.

Since there is a `errors="0"`, maybe it's possible to mark as 'error'?
There is a special scenario I need to mark a test as 'error', how am I supposed to do that?

**Comment by sormuras** [comment]
Already answered at https://github.com/junit-team/junit5/issues/2279

**Comment by mannodermaus** [comment]
@sormuras Thanks for the insight!
