### ISSUE TITLE
Support Task configuration avoidance API

### ISSUE THREAD

**Issue by rciovati** [mannodermaus/android-junit5#216]
While profiling my build I found that some test tasks were created by Gradle even thought they should have not. After digging, I found that the plugin uses the eager APIs that force task creation instead of the [task configuration avoidance APIs](https://docs.gradle.org/current/userguide/task_configuration_avoidance.html).

TBH it's not a huge deal because also the [Kotlin plugin has the same issue](https://youtrack.jetbrains.com/issue/KT-25428) (hopefully it will be fixed in 1.4) but it's a nice enhancement to keep in mind.

**Comment by mannodermaus** [comment]
There is now a pending pull request which migrates all of the plugin's generated tasks to the newer APIs. There may still be some transitive usage of an older function, but hopefully this will improve the performance a little. This will be available on the upcoming SNAPSHOT builds as soon as https://github.com/mannodermaus/android-junit5/pull/235 is merged. Thanks for reporting! 🙏
