### ISSUE TITLE
Jetpack compose support

### ISSUE THREAD

**Issue by noahjutz** [mannodermaus/android-junit5#234]
I would like to use junit 5 to test my jetpack compose project.

A compose test rule is required for setting up the UI and using Testing APIs: [(documentation)](https://developer.android.com/jetpack/compose/testing#setup)
```kotlin
@get:Rule
val composeTestRule = createAndroidComposeRule<MyActivity>()
```

This only works for junit 4. Is there any way to use junit 5 with jetpack compose?

**Comment by mannodermaus** [comment]
Thank you for bringing this up! Unfortunately, test rules are a concept exclusive to JUnit 4 and a new implementation is required to make them work with JUnit 5 (similar to the `ActivityScenario` support we already have). While I have done some work with Jetpack Compose, I haven't had the chance to look into testing and specifically how the `ComposeTestRule` works. In a nutshell, you'd have to convert its content to JUnit 5 extension points such as `BeforeEachCallback` and `AfterEachCallback`.

I might consider ramping up a library for Compose support in the near future, once that API stabilizes a little further. Until then, please continue to write your Compose UI tests against the JUnit 4 APIs. If you don't mind, I'd like to keep this ticket around to keep visibility and gauge interest from people towards this feature. 🙏

**Comment by Nikola-Milovic** [comment]
Any update on this? Compose is [getting its stable release now](https://9to5google.com/2021/05/18/jetpack-compose-1-0-july-material-you/) (currently `1.0.0-rc02`) .

**Comment by mannodermaus** [comment]
Nothing substantial. I did have a look through the test source code of Jetpack Compose a few months ago, unfortunately [leaving quite disappointed](https://twitter.com/marcelschnelle/status/1419994758466965520): There is a lot of tight coupling to JUnit 4 so we'd need to copy-paste and rewrite the entire thing, pretty much. I would've liked some sort of abstraction similar to what recent efforts in `androidx.test` have brought to the table. That's why I'm a little hesitant to fully commit to this right away. I'll give it another look after 1.0 stable is released

**Comment by mannodermaus** [comment]
I was celebrating the stable release of Jetpack Compose by giving the integration another shot. It's a very, very simple example but I managed to create a bridge to Compose via the existing JUnit 4 stuff. Feels great to see a `@ParameterizedTest` driving a Composable <3

There's still a lot to come and I need many more hours to refine this hacky approach, but I'm quite happy about this. 🎉🎉

<img width="605" alt="Screen Shot 2021-07-28 at 20 45 33" src="https://user-images.githubusercontent.com/3897705/127378992-ec98b1a1-83b6-4034-aaa5-6f92e2983615.png">

**Comment by Nikola-Milovic** [comment]
Seems promising!

**Comment by balazsbanyai** [comment]
Looks great! Would you mind sharing the extension's code as a workaround until this feature is released?

**Comment by mannodermaus** [comment]
I've spent a bit of time drafting the initial PR for this and pulled in what I had been experimenting with before. You can get it from Sonatype's snapshot repository:

```kotlin
dependencies {
  androidTestImplementation("de.mannodermaus.junit5:android-test-compose:0.1.0-SNAPSHOT")
}
```

Usage:

```kotlin
class YourTest {
  @RegisterExtension
  @JvmField
  val extension = createComposeExtension()

  @Test
  fun test() {
    extension.setContent {
      // Your composable
    }
  }
}
```

I'll be tracking progress over time over at https://github.com/mannodermaus/android-junit5/pull/257

**Comment by Piotr-Smietana-Intent** [comment]
Also I've noticed another, minor issue - `ComposeContext`, being an alias to `ComposeContentTestRule`, does not allow to directly access to activity (which is defined in `ComposeContentTestRule` implementation, `AndroidComposeTestRule`), like it used in junit4:

junit4:
```
@get:Rule
    val composeTestRule = createAndroidComposeRule<LoginActivity>()

    @Test
    fun test() {
        composeTestRule.activity
    }
```

junit5 has to cast `ComposeContext` to `AndroidComposeTestRule` first, which is not terrible but still inconvenient
```
    @Test
    fun test() = extension.runComposeTest {
        // this won't compile
        //this.activity

        // this works
        (this as AndroidComposeTestRule<*, *>).activity
    }
```

**Comment by mannodermaus** [comment]
Thanks for your feedback, @Piotr-Smietana-Intent! I'm also not quite happy with the extension API for JUnit 5 yet, and your `BeforeEach` example illustrates this pretty well, too.

**Comment by ILikeYourHat** [comment]
Any plans to make this support stable? 🙂

**Comment by hakanai** [comment]
Compose supports more than just Android, too, and those of us writing tests for desktop apps also want a `ComposeExtension` instead of a `ComposeTestRule`.

The cross-platform equivalent of `createAndroidComposeRule<T>()` appears to be just `createComposeRule` - on desktop this returns a `DesktopComposeTestRule` instead of the Android one.

I was attempting to write an extension to replace the test rule for desktop tests, and more or less hit the same problems described here. A lot of the code their test rule is using is internal, so I would end up copying those things into my code as well, and eventually I would have all the code in their module duplicated in mine. :(

I opened [a ticket at compose-jb](https://github.com/JetBrains/compose-jb/issues/2371) asking for them to consider using JUnit 5 instead of 4. The test API is still experimental, so wild changes in how it works are already expected.

**Comment by santansarah** [comment]
I tested this out - this is working great; very cool!

```
@RegisterExtension
@JvmField
val extension = createComposeExtension()
```

I ran into an issue with this:

```
@JvmField
@RegisterExtension
 val extension = createAndroidComposeExtension<MainActivity>()
```

I get an error:   Cannot inline bytecode built with JVM target 11 into bytecode that is being built with JVM target 1.8. Please specify proper '-jvm-target' option

I may have missed something in setup?

Here's a link to my test (along w/the full project): https://github.com/santansarah/sharedtest-junit5-turbine/blob/compose-testing/app/src/androidTest/java/com/santansarah/sharedtestjunit5turbine/compose/ComposeTestActivity.kt

```
Android Studio Flamingo | 2022.2.1 Canary 9
Build #AI-222.4345.14.2221.9321504, built on November 22, 2022
Runtime version: 17.0.4.1+0-b2043.56-9127311 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
```

```
plugins {
    id 'com.android.application' version '8.0.0-alpha09' apply false
    id 'com.android.library' version '8.0.0-alpha09' apply false
    id 'org.jetbrains.kotlin.android' version '1.7.20' apply false
    id 'de.mannodermaus.android-junit5' version '1.8.2.1' apply false
}
```

```
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
```

```
androidTestImplementation 'de.mannodermaus.junit5:android-test-compose:0.1.0-SNAPSHOT'
```

**Comment by Faltenreich** [comment]
@santansarah You have to build against JVM target 11, so change your compile options to:

```
compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '11'
    }
}
```

If it still does not work, check your preferences and ensure that the Kotlin compiler uses the same JVM target. I then had to "Invalidate Caches..." and after a restart of Android Studio, everything worked fine.

**Comment by santansarah** [comment]
Hi @Faltenreich - I changed my compile options to version 11; I also updated my project plugins + dependencies. Everything is working great - thanks so much!
Sarah

**Comment by tuguzD** [comment]
Was `de.mannodermaus.junit5:android-test-compose:0.1.0-SNAPSHOT` removed or am I missing something?

**Comment by mannodermaus** [comment]
No, shouldn't be. 🤔 The Maven Central snapshots repository lists [the data for it](https://oss.sonatype.org/service/local/repositories/snapshots/content/de/mannodermaus/junit5/android-test-compose/maven-metadata.xml) just like before. Please make sure that the repo is available to your module and that Gradle offline mode isn't on by accident (speaking from experience there).

**Comment by mannodermaus** [comment]
Hello everybody! I wanted to share an update for the Compose integration, as I finally had a bit of time to spend on this endeavor over the last couple of nights.

Please update your dependency declarations as follows:

```kotlin
dependencies {
  androidTestImplementation("de.mannodermaus.junit5:android-test-compose:1.0.0-SNAPSHOT")
  androidTestImplementation("org.junit.jupiter:junit-jupiter-api:5.9.3")
  debugImplementation("androidx.compose.ui:ui-test-manifest:1.4.3")
}
```

Also, make sure to use the latest Gradle plugin for JUnit 5 (`1.9.3.0`). Then, you should be able to use the revamped `ComposeExtension` in your instrumentation tests, literally:

```kotlin
class MyTests {
  @JvmField
  @RegisterExtension
  @ExperimentalTestApi
  val extension = createComposeExtension()
  // or, if you want to test your own Activity:
  // val extension =  createAndroidComposeExtension<MyActivity>() 

  @BeforeEach
  fun beforeEach() {
    extension.use {
      // You can do set-up logic here...
    }
  }

  @Test
  fun test() {
    extension.use {
      // ...and run the actual test here!
      setContent {
        Button(onClick = {}) {
          Text("button")
        }
      }

      onNodeWithText("button").performClick()
    }
  }
}
```

`runComposeTest` is now a synonym for `use`, but was deprecated in the latest snapshot and will be removed in a stable release.

There may very well be a bunch of cases that aren't working 100% yet, so please keep letting me know about those. 🥳

**Comment by jama5262** [comment]
@mannodermaus 

I can't seem to find `de.mannodermaus.junit5:android-test-compose:1.0.0-SNAPSHOT`

https://mvnrepository.com/artifact/de.mannodermaus.junit5

**Comment by compscidr** [comment]
This is working great so far, thanks! I was wondering if its possible to have the Activity start with a particular intent?

**Comment by mannodermaus** [comment]
The inaugural version of Compose, including the additions by @compscidr, have been released! To keep in line with the versioning of the other instrumentation libraries, I bumped the Compose artifact to `1.4.0` as well:

```kotlin
dependencies {
  androidTestImplementation("de.mannodermaus.junit5:android-test-compose:1.4.0")
}
```

**Comment by mannodermaus** [comment]
> Thanks, this is great! Should I expect it to work for Compose Desktop?

No, this project is solely confined to Android and this includes the Compose support.

> I am getting a warning that is requeiring me to use @Suppress("JUnitMalformedDeclaration")

This warning can be disregarded, but it definitely is a bug. I've filed #318 for it, thanks for bringing it up!

**Comment by lukaszkalnik** [comment]
When using this together with https://github.com/apter-tech/junit5-robolectric-extension I get the following error:

```
java.lang.UnsupportedOperationException: main looper can only be controlled from main thread
	at org.robolectric.shadows.ShadowPausedLooper.executeOnLooper(ShadowPausedLooper.java:692)
	at org.robolectric.shadows.ShadowPausedLooper.idle(ShadowPausedLooper.java:104)
	at org.robolectric.android.internal.RoboMonitoringInstrumentation.waitForIdleSync(RoboMonitoringInstrumentation.java:85)
	at androidx.test.core.app.ActivityScenario.moveToState(ActivityScenario.java:649)
	at androidx.test.core.app.ActivityScenario.close(ActivityScenario.java:416)
	at de.mannodermaus.junit5.compose.AndroidComposeExtension.afterEach(AndroidComposeExtension.kt:176)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	```

**Comment by leggomymeggos** [comment]
@lukaszkalnik Same here; I'm also trying to use that library to update my Robolectric tests.

@mannodermaus Here's a sample test class that ends up throwing the `main looper can only be controlled from main thread` error:
```kotlin
import androidx.compose.material.Text
import androidx.compose.ui.test.ExperimentalTestApi
import androidx.compose.ui.test.assertIsDisplayed
import androidx.compose.ui.test.onNodeWithText
import de.mannodermaus.junit5.compose.createComposeExtension
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.extension.ExtendWith
import org.junit.jupiter.api.extension.RegisterExtension
import tech.apter.junit.jupiter.robolectric.RobolectricExtension

@OptIn(ExperimentalTestApi::class)
@ExtendWith(RobolectricExtension::class)
class SampleTest {
    @Suppress("JUnitMalformedDeclaration")
    @JvmField
    @RegisterExtension
    val extension = createComposeExtension()

    @Test
    fun `Given a string, then it is displayed`() = extension.use {
        setContent {
            Text("Hello")
        }

        onNodeWithText("Hello").assertIsDisplayed()
    }
}
```

I'm generally really excited for this library because it means that all of my project's UI tests could use JUnit5! This exception in Robolectric tests is a big blocker though

**Comment by mannodermaus** [comment]
Thanks for the added information! I have no resources to dedicate to this at the moment, but have created #340 to keep track of it. As this new trace is unrelated to Compose, let's put this ticket to rest and continue over there. 🙇‍♂️

**Comment by LloydBlv** [comment]
I annotated my tests with the good old `@RunWith(RobolectricTesRunner::class)` happily 😄  and always got a green even for all my failing tests until I realized I needed to use `@ExtendWith(RobolectricExtension::class)` instead. then I got the "main looper can only be controlled from main thread" error
```
//Always gets passed for any type of assertions
@RunWith(RobolectricTestRunner::class)
class ErrorViewUiTests {
    @OptIn(ExperimentalTestApi::class)
    @Rule
    val composeTestRule = createComposeExtension()

```

**Comment by vincent-paing** [comment]
> Yes, I haven't tried it in a while but my assumption based on vague memory of past experiences is that Robolectric is not compatible with this library (at least for Compose)
> 
> If this library could be compatible with robolectric, there might be hope one day for running unit tests (not instrumented) for compose with JUnit 5.
> 
> Currently, I have a hacky way to run some compose unit tests (not instrumented) in JUnit 5 with this plugin, and without robolectric. But it doesn't work for all components, and it involved a lot of hacky trial and error that I wouldn't recommend to anyone. I decided in the end to just be patient for more updates either from here or from the standard android test library.

We have a community plugin for robolectric now :D https://github.com/apter-tech/junit5-robolectric-extension
