### ISSUE TITLE
Parallel test execution

### ISSUE THREAD

**Issue by realdeadfish** [mannodermaus/android-junit5#24]
With junit 4 tests we had the ability to configure the number of Java process forks that would run a big test suite and therefor speed the run up substantially. This was possible via 

```groovy
testOptions.unitTests.all {
      maxParallelForks 2 
}
```

Each fork normally uses four threads (afaik this is some internal junit configuration that cannot be changed), so this setup would lead to a total of 8 threads running a test suite.

Unfortunately, with the android-junit5 plugin, the above configuration no longer works. Do you know an alternative how to configure this now? I also cannot find any reference to it in the `junitPlatform` DSL of the [official Gradle plugin](https://github.com/junit-team/junit5/tree/master/junit-platform-gradle-plugin).

**Comment by mannodermaus** [comment]
As far as I know, support for parallelism hasn't made it into JUnit 5.0 GA, and is instead scheduled as part of the 5.x backlog. Therefore, there's no DSL similar to what you mentioned for either plugin at this point. [I dug up the related issue in the main project](https://github.com/junit-team/junit5/issues/964), to which I also subscribed back when it was opened, but it seems like there's no real ETA on that just yet.

**Comment by realdeadfish** [comment]
OK, many thanks for the info!

**Comment by mannodermaus** [comment]
With the release of Gradle 4.6 and its first-party support, this could potentially work out-of-the-box once we upgrade to the new native APIs. I'm temporarily scheduling this for inspection in the next dev cycle.

**Comment by 13Dima13** [comment]
No, it is still does not work not in Maven and neither Gradle

**Comment by dpreussler** [comment]
@mannodermaus  as discussed here it should work:
https://github.com/junit-team/junit5/issues/964

**Comment by mannodermaus** [comment]
After a quick check with the latest plugin (`1.2.0.0`), I can confirm that `maxParallelForks` does indeed work as intended with JUnit `5.3.0-RC1`. This doesn't apply to users of android-junit5 `1.0.32` and earlier, as those versions still use the legacy implementation instead of the native Gradle integration.
