### ISSUE TITLE
Enable Plugin Marker Artifact to support plugin DSL

### ISSUE THREAD

**Issue by G00fY2** [mannodermaus/android-junit5#244]
Hi, thanks for your work! This issue is similar to #166 

### Issue:
To support plugin DSL (required for type-safe model accessors when using kts) every gradle plugin needs to declare a  [Plugin Marker Artifact](https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_markers).

**The plugin seems to be lacking the Plugin Marker Artifact .** Normally the `java-gradle-plugin` takes care of configuring the marker. I am not sure if this is because you disabled [isAutomatedPublishing](https://github.com/mannodermaus/android-junit5/blob/389a8eb857d156faeead77bf4620f885bddb73bb/plugin/android-junit5/build.gradle.kts#L45) or if some configuration is missing. From what I remember this should work pretty much out of the box.

Currently your plugin forces developers that use the plugin DSL to [configure a custom resolution strategy](https://docs.gradle.org/current/userguide/custom_plugins.html#note_for_plugins_published_without_java_gradle_plugin).

Plugin Version: 1.7.1.1
Gradle Version: 6.8.3

### Steps to reproduce:
- use plugin DSL to resolve and apply the plugin

**Comment by mannodermaus** [comment]
Hey, thanks for bringing this up and apologies for the late reply! I've been wanting to look into the `plugins` block for the longest time, and with kts becoming more and more widespread, I think it's time we tackled this. 💪

**Comment by Legion2** [comment]
what is the status of this, we are currently migrating to only using the plugins block and facing issues with this plugin.

**Comment by mannodermaus** [comment]
From plugin version 1.8.0.0 onwards, automated publishing of the Plugin Marker artifact will be done. In fact, `1.8.0.0-SNAPSHOT` already does this right now if you're able to pull from Sonatype's snapshot repository. I'll be releasing the stable, non-snapshot release over the weekend.

**Comment by mannodermaus** [comment]
Released in 1.8.0.0

**Comment by Legion2** [comment]
Thanks
