### ISSUE TITLE
AGP 7.0+ reports obsolete usage of DSL element 'dexOptions'

### ISSUE THREAD

**Issue by justasm** [mannodermaus/android-junit5#258]
Including a classpath dependency on `de.mannodermaus.gradle.plugins:android-junit5:1.7.1.1` causes Android Gradle Plugin version 7.0 and above to report the following warning for each module during Gradle's configuration phase:

```
DSL element 'dexOptions' is obsolete and should be removed.
It will be removed in version 8.0 of the Android Gradle plugin.
Using it has no effect, and the AndroidGradle plugin optimizes dexing automatically.
```

**Comment by mannodermaus** [comment]
The Gradle plugin does not deal with nor care about the consumer application's usage of `dexOptions`. Are you positive that this is caused by it? In other words, if you removed the declaration of `android-junit5`, the message would disappear?

**Comment by justasm** [comment]
You're correct, I could not reproduce the warning with the android-junit5 plugin in isolation.

Taking a fresh look, I tracked down the dexOptions warning to a task in our project’s buildscript that called `project.properties["android"].properties["resourcePrefix"]`. Changing it to `android.resourcePrefix` seems to have resolved the issue. I’m at a bit of a loss as to the difference, but happy to get rid of the warning.

Apologies for wasting your time, thanks for responding and for your work on this project!
