### ISSUE TITLE
Add support for auto registering extensions

### ISSUE THREAD

**Issue by yschimke** [mannodermaus/android-junit5#261]
Defining an extension in src/main/resources/META-INF/services/org.junit.jupiter.api.extension.Extension

Doesn't work for Android Junit5 tests.

It is still required to use @ExtendWith(MockWebServerExtension.class)

**Comment by mannodermaus** [comment]
Sorry for the late response. Instrumentation tests do not pick up the parameters specified in the `junitPlatform` block for unit tests. However, you can specify them explicitly for instrumentation tests. In the case of auto-registered extensions, the setup could look like this:

```kotlin
android {
  defaultConfig {
    // You already have this:
    testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    testInstrumentationRunnerArguments["runnerBuilder"] = "de.mannodermaus.junit5.AndroidJUnit5Builder"

    // But you can add config parameters like this:
    testInstrumentationRunnerArguments["configurationParameters"] = "junit.jupiter.extensions.autodetection.enabled=true"
  }
}
```

Jupiter should pick up any extension registered via `ServiceLoader` automatically now.
