### ISSUE TITLE
Log not working with ParameterizedTest

### ISSUE THREAD

**Issue by hellday** [mannodermaus/android-junit5#311]
Hello,
Test annotated with `@ParameterizedTest` don't show any logs.
I tested it with Log class and the `println()` method from Kotlin.

It's working fine on a test annotated with `@Test`.

**Comment by mannodermaus** [comment]
Hi, apologies for the late response. When you say that this test "doesn't show any logs", do you mean the Test window in Android Studio, or do you mean that even Logcat doesn't show anything? To verify, please check if you can find your log statements inside Logcat when the test is executed (you can filter Logcat with `tag:System.out` to find the `println()` messages). If they show up in Logcat but not in the AS Test window, then we can fold this ticket into #312.
