### ISSUE TITLE
Readme should include apply plugin for legacy syntax

### ISSUE THREAD

**Issue by peterdk** [mannodermaus/android-junit5#313]
I was struggling to get my Junit5 tests detected, and it turned out that the readme didn't tell me to actually:
```
apply plugin: 'de.mannodermaus.android-junit5'
```
I am using the legacy Gradle setup, and this is not mentioned there.
When I do not apply the plugin in my target build.gradle then it won't find the junit 5 tests.

I'll look if I can make a PR for adding this, since it took me an hour to figure out.

**Comment by mannodermaus** [comment]
Thanks for reporting. It makes sense to include the `apply` statement for legacy Groovy clients. Thank you as well for preparing a PR! I took it and reorganized the contents into a single block per language, as I prefer that over the multi-block approach. I'll merge #315 once CI clears it!
