### ISSUE TITLE
sumas

### ISSUE THREAD

**Issue by ecuzma** [mannodermaus/android-junit5#333]
import static org.junit.jupiter.api.Assertions.assertEquals;

import example.util.Calculator;

import org.junit.jupiter.api.Test;

class MyFirstJUnitJupiterTests {

    private final Calculator calculator = new Calculator();

    @Test
    void addition() {
        assertEquals(2, calculator.add(1, 1));
    }

}

**Comment by mannodermaus** [comment]
?
