### ISSUE TITLE
Incompatible waitUntil method signature for compose ui test 1.7.0 (since alpha02)

### ISSUE THREAD

**Issue by F43nd1r** [mannodermaus/android-junit5#353]
Trying to use `waitUntil` with any version newer than `1.7.0-alpha01` of `androidx.compose.ui:ui-test` leads to a missing method error due to a signature change. (It now also has a description string)

Please update the signature of `waitUntil` to match the androidx library. 

Side note: Due to the `ComposeContext` wrapper extension functions like `waitUntilNodeCount` are not available. Maybe you could provide versions of these as well?

**Comment by mannodermaus** [comment]
I was about to comment that I'd like to wait until 1.7 is stable, but lo and behold, it was released today. 👀 Should be a fairly straightforward update.

**Comment by mannodermaus** [comment]
The Compose BOM for September is out and links against Compose 1.7.0. I'll get to work. 😎

**Comment by mannodermaus** [comment]
This is available in the latest snapshots now. You can either update your android-junit5 plugin to `1.11.0.1-SNAPSHOT`, or stick to the stable plugin and manually change the instrumentation library version that it links to:

```kotlin
junitPlatform {
  instrumentationTests.version.set("1.6.0-SNAPSHOT")
}
```
