### ISSUE TITLE
Add reference to `InstantExecutorExtension` to the README

### ISSUE THREAD

**Issue by neboskreb** [mannodermaus/android-junit5#355]
Append section `Extensions` of the README with the reference to `InstantExecutorExtension`.

This extension implements support for LiveData testing in JUnit5, as discussed in https://github.com/mannodermaus/android-junit5/issues/66

Users of `android-junit5` will certainly find useful to have a quick ref rather than googling it (again).

**Comment by neboskreb** [comment]
@mannodermaus Poster a PR for this ticket: #356 
Please review when you have time!

**Comment by mannodermaus** [comment]
This is now available on the main repository page. Thank you for your contribution!
