### ISSUE TITLE
Please publish 1.6.0 release notes

### ISSUE THREAD

**Issue by TWiStErRob** [mannodermaus/android-junit5#357]
I got a PR https://github.com/TWiStErRob/net.twisterrob.colorfilters/pull/368
but don't see 1.6.0 release: https://github.com/mannodermaus/android-junit5/releases

**Comment by mannodermaus** [comment]
I went to sleep just after starting deployment. In that sense, good morning I suppose!

**Comment by TWiStErRob** [comment]
Hah, good morning, sounds way too familiar! 🫣
Thank you!
