### ISSUE TITLE
Trying to hook into the created tasks

### ISSUE THREAD

**Issue by Rosomack** [mannodermaus/android-junit5#40]
I'm trying to set up HTML reporting for my tests. I've noticed that the test tasks are generated in `project.afterEvaluate`. This is the exact same hook I use to find the test tasks, so it's a bit of a chicken-and-egg problem - it works on the command line for some reason but fails in Android Studio - can't find the test tasks.

I use something like
```
project.afterEvaluate {
    if (project.coverage.includes == null) {
        project.coverage.includes = []
    }

    // Grab all build types and product flavors
    def buildTypes = android.buildTypes.collect { type ->
        type.name
    }
    def productFlavors = android.productFlavors.collect { flavor ->
        flavor.name
    }

    // When no product flavors defined, use empty
    if (!productFlavors) productFlavors.add('')

    def coverageTasks = []

    buildTypes.each { buildTypeName ->
        productFlavors.each { productFlavorName ->
            def capitalizedVariantName
            if (!productFlavorName) {
                capitalizedVariantName = "${buildTypeName.capitalize()}"
            } else {
                capitalizedVariantName = "${productFlavorName.capitalize()}${buildTypeName.capitalize()}"
            }
            def testTaskName = "junitPlatformTest${capitalizedVariantName}"

            // Add HTML reports for JUnit 5
            tasks[testTaskName].finalizedBy 'junitHtmlReport'
        }
    }

    tasks['junitPlatformTest'].finalizedBy 'junitHtmlReport'
}
```

Do you have any better suggestion on how I can hook this up?

**Comment by mannodermaus** [comment]
Yeah, unfortunately we need to evaluate the project first, in order to generate the required tasks based on the assembled Android environment.

The Android Plugin's `testOptions` make use of a Gradle `DomainObjectSet` for its lazy configuration, so that would be a good addition for us as well. The DSL for your integration could look like this:

```groovy
android {
  testOptions {
    junitPlatform.unitTests.all {
      // Provided with a JUnit 5 Unit Test task, apply your configuration
      it.finalizedBy "junitHtmlReport"
    }
  }
}
```

You could use `all` at any point during the configuration or evaluation phase, and it would apply the closure to all existing and future tasks added by the plugin.

Let me know if that would work for your use case!

**Comment by mannodermaus** [comment]
The proposed API is going to be part of the `1.0.23` release. You can try it now using the latest `SNAPSHOT` as well!

**Comment by Rosomack** [comment]
You've been fantastically helpful! Thanks, I will test the snapshot soon.

**Comment by Rosomack** [comment]
This does not seem to work for me ie. it configures fine but the `junitHtmlReport` task doesn't run after the tests complete.

```
apply plugin: 'de.mannodermaus.android-junit5'
apply plugin: 'com.kncept.junit5.reporter'

android {
    sourceSets {
        test.java.srcDirs += 'src/test/kotlin'
    }

    testOptions {
        // Setting up JUnit 5 and Spek
        junitPlatform {
            filters {
                engines {
                    include 'spek' // Configure spek's TestEngine to be detected by JUnit 5
                    include 'junit-vintage'// Configure the vintage (JUnit 4) TestEngine to be detected by JUnit 5
                }
            }
            unitTests.all {
                // Provided with a JUnit 5 Test task, apply your configuration
                it.finalizedBy 'junitHtmlReport'
            }
        }
    }
}
```

**Comment by mannodermaus** [comment]
That's odd, using the sample project in this repository, I'm able to run my dependent task using `finalizedBy` just fine:

```groovy
buildscript {
  repositories {
    jcenter()
    maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
  }

  dependencies {
    classpath "de.mannodermaus.gradle.plugins:android-junit5:1.0.23-SNAPSHOT"
  }
}

apply plugin: "com.android.application"
apply plugin: "kotlin-android"
apply plugin: "de.mannodermaus.android-junit5"

task someTask << {
  println "HUH?"
}

android {
  testOptions {
    junitPlatform {
      unitTests.all {
        it.finalizedBy "someTask"
      }
    }
  }
}
```

```
./gradlew :sample:junitPlatformTest
(...)
Test run finished after 4330 ms
[        10 containers found      ]
[         0 containers skipped    ]
[        10 containers started    ]
[         0 containers aborted    ]
[        10 containers successful ]
[         0 containers failed     ]
[        20 tests found           ]
[         2 tests skipped         ]
[        18 tests started         ]
[         0 tests aborted         ]
[        18 tests successful      ]
[         0 tests failed          ]

:sample:junitPlatformTest
:sample:someTask
HUH?
```

**Comment by Rosomack** [comment]
Thanks, I'll keep digging.

**Comment by Rosomack** [comment]
Yep, it works. Turns out the junit reporting plugin was failing silently, so I didn't see any reports.

I've noticed two confusing things though:
1. Sometimes the junit result summery is not printed to the console.
2. More confusingly, the finaliser task sometimes does not print either despite executing properly.

Might this be related to Android Gradle Plugin 3.0.1 ?

**Comment by mannodermaus** [comment]
Re 1: The test tasks are incremental, so repeated invocation without modified inputs and outputs (i.e. source code changes) will simply skip their execution (since to them, there's nothing that could've changed). That might also be why you wouldn't see a test summary output in these cases. 
Re 2: I'm not entirely sure about the intricacies of the Gradle `finalizedBy` statement, but I would assume that finalizers aren't being triggered either when their dependent task is already `UP-TO-DATE`.

**Comment by Rosomack** [comment]
I'm running clean build... build cache shenanigans?

**Comment by mannodermaus** [comment]
Mhh, in a `clean build`, all of what I just said shouldn't be happening. Quite strange indeed!

**Comment by Rosomack** [comment]
It all gets printed if I use `--info` though! 😕 ...

Anyway I'll stop bothering you. Thanks, you've been very helpful!
