### ISSUE TITLE
Android tests run not working after applying unitTestsRuntime

### ISSUE THREAD

**Issue by alexanderbratusenko** [mannodermaus/android-junit5#41]
After applying unitTestsRuntime() in gradle AS3 doesnt run android tests as android test and run it as unit test without asking (as it was before)

**Comment by mannodermaus** [comment]
I can't repro this with the sample project in this repository. How are you setting up your dependencies? Can you share the Run Configuration you're trying to execute?

**Comment by mannodermaus** [comment]
Feel free to reopen if necessary
