### ISSUE TITLE
Interop between src/java and src/kotlin

### ISSUE THREAD

**Issue by Rosomack** [mannodermaus/android-junit5#42]
Right, I don't know if this is an issue with this plugin or our general setup but here goes:

We have a test class under `src/test/kotlin/Test.kt`. It references a test helper class located in `src/test/java/Helper.java`

This is in an `Android library module`.

The tests fail to compile, the kotlin class cannot see the java class. We get `UnresolvedReference` errors for anything from the `src/kotlin` folder that refers to stuff from `src/java`.

**Comment by Rosomack** [comment]
If I add 
```
sourceSets {
        test.java.srcDirs += 'src/test/kotlin'
        test.kotlin.srcDirs += 'src/test/java'
}
```

I don't get `UnresolvedReference` any more, but I get `NoClassDefFound` at runtime. This leads me to guess the problem is related to copying the test classes around.

**Comment by Rosomack** [comment]
I've kind of sidestepped the problem by moving all kotlin files into `src/java`.

**Comment by mannodermaus** [comment]
The plugin doesn't copy Kotlin classes anymore (that was legacy behavior removed in `1.0.20`), so this is not where the issue comes from. Therefore, I'm thinking that it might be unrelated to the plugin. Can you verify that a JUnit 4 test can successfully reach over to Java?
