### ISSUE TITLE
Can't exclude classes from JaCoCo code coverage report

### ISSUE THREAD

**Issue by ebrowne72** [mannodermaus/android-junit5#43]
JaCoCo includes all classes in its report. To exclude classes, the plug-in needs to set the task's class directories like this:

```
reportTask.classDirectories = project.fileTree(
	dir: <destinationDir>,
	excludes: ['**/R.class', '**/R$*.class']
)
```

**Comment by mannodermaus** [comment]
Thanks for reporting! We should allow users to provide their own exclude rules on top of the default set you mentioned, too.

**Comment by mannodermaus** [comment]
This will be part of the `1.0.23` release. You can try the latest `SNAPSHOT` to get early access to this feature. If you want to have additional exclusion rules, use the new DSL:

```groovy
android.testOptions {
  junitPlatform {
    jacoco {
      excludedClasses += ["SomePattern.class"]
      excludedSources += ["SomeFile.java"]
    }
  }
}
```

**Comment by mannodermaus** [comment]
I will shortly release `1.0.30`, where this will be included.
