### ISSUE TITLE
Jacoco executes tests for all build variants

### ISSUE THREAD

**Issue by youngam** [mannodermaus/android-junit5#47]
When I'm using plugin jacoco executes tests for all build variants. I specified that jacocoTestReport only depends on one task with name "test${testBuildVariantName.capitalize()}UnitTest", but when I run task it executes tests for all build types. I started watch source code of plugin, but will be thankful if you point me to the right direction to increase this process

**Comment by mannodermaus** [comment]
The `jacocoTestReport` task executes Jacoco for all build types by default. Additionally, there are more tasks that only run code coverage for a single build type. You should be able to utilize the `jacocoTestReportDebug` and `jacocoTestReportRelease` for this purpose (any other custom type you have will also have its equivalent)!
