### ISSUE TITLE
Jacoco tasks customization

### ISSUE THREAD

**Issue by youngam** [mannodermaus/android-junit5#56]
Hi, have a small problem when use plugin: I need to add custom exclude to jacocoTestReportDebug coverage. Is there any way to do this?
When I try to define the same task generated by plugin gradle give me the error that task with this name already exists.

```groovy
task "jacocoTestReport${buildVariantName.capitalize()}"(type: JacocoReport, dependsOn: testTaskName) {
    group = "Reporting"
    description = "Generate Jacoco coverage reports"

    classDirectories = fileTree(
            dir: "$buildDir/intermediates/classes/$buildVariantName",
            // want to see coverage only to specific packages, classes            
            include: [
                    '**/MathUtils.class'
            ]
    )

    def mainSrc = "${project.projectDir}/src/main/java"

    sourceDirectories = files([mainSrc])
    executionData = files("${buildDir}/jacoco/${testTaskName}.exec")

    reports {
        html.enabled = true
    }
}
```

And the second question: I don't need to create jacoco tasks for all build variants.Is it possible to prevent  plugin from generating this tasks? Is there possibility to manage jacoco tasks only in client code?

**Comment by mannodermaus** [comment]
The plugin allows you to specify custom exclude rules for both source & class files:

```groovy
android.testOptions {
  junitPlatform {
    jacocoOptions {
      // Additional exclusion rules for Code Coverage Reports -
      // by default, R.class & BuildConfig.class are excluded.
      excludedClasses += []
      excludedSources += []
    }
  }
}
```

There is currently no way to disable the generation of these companion tasks in the DSL. It's reasonable to be able to specify only a subset of variants to generate, though, and I'll consider it for a future release. If you really have to use your own custom `JacocoReport` task, consider giving it a different name that doesn't clash with the ones generated by the plugin.

**Comment by youngam** [comment]
@mannodermaus thank you for fast response. I consider variant of creating task with different name for Jacoco. But I don't like that there are too much tasks in project that I don't use. Anyway this is my vision. Thanks again.

**Comment by mannodermaus** [comment]
This will be part of the 1.0.31 release!
