### ISSUE TITLE
Suggestions for porting InstantTaskExecutorRule?

### ISSUE THREAD

**Issue by autonomousapps** [mannodermaus/android-junit5#66]
JUnit5 does not support `Rule`s. Yet some tests, particularly Android tests, absolutely require `Rule`s. One example is the `InstantTaskExecutorRule` required for unit testing `ViewModel`s. I'm interested in writing a custom Extesnsion, but I don't really know where to start. Any ideas? Does this already exist?

**Comment by autonomousapps** [comment]
Actually, turns out it wasn't so hard to replace that particular rule. Here it is:
```
class InstantTaskExecutorExtension : BeforeEachCallback, AfterEachCallback {

    override fun beforeEach(context: ExtensionContext) {
        ArchTaskExecutor.getInstance().setDelegate(object : TaskExecutor() {
            override fun executeOnDiskIO(runnable: Runnable) {
                runnable.run()
            }

            override fun postToMainThread(runnable: Runnable) {
                runnable.run()
            }

            override fun isMainThread(): Boolean {
                return true
            }
        })
    }

    override fun afterEach(context: ExtensionContext?) {
        ArchTaskExecutor.getInstance().setDelegate(null)
    }
}
```

**Comment by mannodermaus** [comment]
Great to see you dived into the Extension sphere yourself already! With the instrumentation test support, I intend to provide replacements for JUnit 4 APIs that evolve to become Extensions. Since this particular class is tied to Architecture Components, I won't include it into the core instrumentation-test library. However, this could become its own library for people to plug into their project eventually. For now, I'll consider to link to this for the upcoming wiki on usage with Instrumentation Tests. Thank you!

**Comment by autonomousapps** [comment]
I can confirm that extension works perfectly in my unit test suite. I'll keep an eye on this project and contribute any other extensions I come across (actually, I already have one to enable the `@Mock` annotation, but I found that elsewhere). I'm sure some way or other we'll end up with some test libs to share!

**Comment by neboskreb** [comment]
@autonomousapps , I guess you'll be glad to know that AFTER 6 YEARS someone finally got time to package it and publish :))))

And you guys too :) 
@Marchuck, @manoellribeiro, @kotako, @filipkowicz, @RBusarow, @ZHAILUJIA, @ravikumar-n, @Marchuck, @zeinabmohamed, @hirokihokari, @manoellribeiro, @vincent-paing

See #355 for more details

**Comment by mannodermaus** [comment]
@neboskreb Thanks for the link! I'll address the PR in its own ticket, but just as a heads-up, that repository doesn't seem to be public. Could you double-check the visibility to non-contributors on it?

**Comment by neboskreb** [comment]
Oops, indeed, I forgot to open it after the release.
Fixed. It's public now!
