### ISSUE TITLE
The filename or extension is too long

### ISSUE THREAD

**Issue by jakob-grabner** [mannodermaus/android-junit5#68]
I'm not entirely sure that this plugin is causing my problems, but I'm unable run my tests via gradle on the console. It works if I run them via android studio, but if I try to run the gradle task manually it fails with `java.io.IOException: CreateProcess error=206, The filename or extension is too long`. 
This seems to be a known problem on windows [Mitigate Long Path Issues Automatically #1989](https://github.com/gradle/gradle/issues/1989).

Also if I disable the plugin executing the test works (But only junit4 tests are executed...).

Entire stacktrace:
[stacktrace.txt](https://github.com/mannodermaus/android-junit5/files/1818981/stacktrace.txt)

**Comment by mannodermaus** [comment]
As far as I understand from a bit of googling regarding this issue, this seems to target Windows specifically. This plugin uses `JavaExec` tasks to run the JUnit Platform, so it is subject to this error when there is a lot of stuff in your classpath.

I found [this plugin](https://github.com/viswaramamoorthy/gradle-util-plugins) which hooks into `JavaExec` tasks and extracts their classpath into a JAR file, compressing the path significantly. Can you check if this works for your case?

**Comment by mannodermaus** [comment]
I'm closing this for now. Feel free to reopen if necessary!
