### ISSUE TITLE
How to generate an HTML report?

### ISSUE THREAD

**Issue by autonomousapps** [mannodermaus/android-junit5#75]
I see the XML output, but I don't see anyway to configure the plugin to output HTML. Is that supported?

**Comment by mannodermaus** [comment]
The default integration only generates XML reports for the executed JUnit 5 tests right now. Supporting the default output format only came recently with the move to first-class JUnit 5 support in Gradle 4.6. Now, the JUnit Platform can be integrated mapped to `Test` tasks, which do support HTML output. I haven't found the time to update the Android plugin to this new architecture yet, though, so for now you'd have to make do with a manual solution. [Here is an approach from JUnit's Sam I found on SO](https://stackoverflow.com/a/39455463/2776126), maybe that works for you as a temporary solution as well? I'm tracking the migration to Gradle 4.6 in #62 if you want to keep a tab on my progress

**Comment by autonomousapps** [comment]
I appreciate the links.

**Comment by Ghedeon** [comment]
As #62 is closed now, does that automatically results in supporting HTML reports?

**Comment by mannodermaus** [comment]
Yes, this will be coming out-of-the-box with the upcoming release!
