### ISSUE TITLE
Unit testing with Java 8 features

### ISSUE THREAD

**Issue by autonomousapps** [mannodermaus/android-junit5#85]
I just wanted to share something I discovered that might help others. I wanted to write parameterized tests using `Stream.of()` and `Arguments.of()`. Those obviously require a Java 8+ build target. You can do the following:

```
// in root build.gradle
allprojects {
    // We need this to use certain features of JUnit5 (such as calling static methods on interfaces)
    tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).matching { "$it".contains("UnitTest") }.all {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8

        kotlinOptions {
            jvmTarget = '1.8'
        }
    }
}
```

Obviously I'm using Kotlin here. I had an earlier iteration of this script that didn't have the `matching` block, and it broke on earlier versions of Android :) But this seems to work just fine.

**Comment by mannodermaus** [comment]
Thanks for the heads-up! This will be nice to have in a wiki on this repository in the near future.

**Comment by autonomousapps** [comment]
Yup! Removed and still works. Thanks for the heads-up. For posterity, this is the block now:
```
// in root build.gradle
allprojects {
    // We need this to use certain features of JUnit5 (such as calling static methods on interfaces)
    tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).matching { "$it".contains("UnitTest") }.all {
        kotlinOptions {
            jvmTarget = '1.8'
        }
    }
}
```

**Comment by mannodermaus** [comment]
This is now included as part of the new [Getting Started](https://github.com/mannodermaus/android-junit5/wiki/Getting-Started) guide. Thanks again!
