### ISSUE TITLE
Run tests via Android Studio in particular folder fails

### ISSUE THREAD

**Issue by brainail** [mannodermaus/android-junit5#89]
Hi :slightly_smiling_face: Sorry that I bother you but I really want to add _junit5_ support for our project and also write them in kotlin plus still have ability to run _junit4_ tests all together. 

I decided to write your directly even if it’s not so polite in some ways :slightly_smiling_face: But in such way it might be faster. 

So, let me describe my actions and the problem: 
- I managed to run all tests all together (with your setup guide) but before it I had the same issue as here: https://github.com/mannodermaus/android-junit5/issues/72 (Even after your fix for this) but what I discovered that if I apply kotlin plugin before yours then everythng works fine (via console *./gradlew junitPlatformTestDebug*). All java/kotlin tests written in junit4 (and some of them in junit5 for experiments) runs and I see the results. 
- When I run one separated test class (with bunch of tests) via Android Studio and it doesn’t matter in what way it’s written (junit4, junit5, java, kotlin) everything works pretty fine. 
- *The problem No. 1*: If I run one single test (via play button to the left of the test method name on side panel) then I still receive the same WARNING as before and no results:
```java
Apr 27, 2018 12:24:18 PM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
WARNING: TestEngine with ID 'junit-jupiter' failed to discover tests
org.junit.platform.commons.util.PreconditionViolationException: Could not find method with name [transferred_backupProcessPhaseReportsProgress_respondShowHalfProgress] in class [com.cococo.manager.SyncBetweenDevicesManagerTest].
	at org.junit.platform.engine.discovery.MethodSelector.lambda$lazyLoadJavaMethod$2(MethodSelector.java:177)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.junit.platform.engine.discovery.MethodSelector.lazyLoadJavaMethod(MethodSelector.java:175)
	at org.junit.platform.engine.discovery.MethodSelector.getJavaMethod(MethodSelector.java:142)
	at org.junit.jupiter.engine.discovery.DiscoverySelectorResolver.lambda$resolveSelectors$3(DiscoverySelectorResolver.java:62)
	at java.util.ArrayList.forEach(ArrayList.java:1251)
	at org.junit.jupiter.engine.discovery.DiscoverySelectorResolver.resolveSelectors(DiscoverySelectorResolver.java:61)
	at org.junit.jupiter.engine.JupiterTestEngine.resolveDiscoveryRequest(JupiterTestEngine.java:68)
	at org.junit.jupiter.engine.JupiterTestEngine.discover(JupiterTestEngine.java:61)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:130)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:117)
	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:82)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:48)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
```

and the the same for vintage

```java
WARNING: TestEngine with ID 'junit-vintage' failed to discover tests
```

- *The problem No. 2*: When I run the whole folder (like 4 classes with tests in each of them) via Android Studio then things becomes weird. First of the whole process  takes really long time to start/Instantiate and Running phase too (looks like it doesn’t search tests in the right folder and instead of it scans the whole project). Secondly no tests found (except junit5 tests - they still run fine! which are located in another folder). And in addition during the whole process (please notice it happens only when I run tests for some folder and not for single one) lots of the following warnings appear in logs:

```java
Apr 27, 2018 12:30:36 PM org.junit.platform.commons.util.ClasspathScanner logGenericFileProcessingException
WARNING: Failed to load java.lang.Class for path [.../submoduleXXX/GooglePlay/build/intermediates/classes/debug/com/google/android/gms/R$dimen.class] during classpath scanning.
java.lang.IncompatibleClassChangeError: com.google.android.gms.R and com.google.android.gms.R$dimen disagree on InnerClasses attribute
```

It looks like when I run it for some folder then it works in another way and try to find out tests in the whole project with wrong classpath and for some reasons it's still able to find Junit5 tests even in other folders.

You might think why? Yes I’m able to run them via console but sometimes I wanna run some particular test of folder and I will prefer to make it stable… 

Maybe it's just the problem of Android Studio..

**Env:**
- Android Studio 3.1.2

```gradle
// tests dependencies
    globalTestsJunitVersion = '4.12'
    globalTestsMockitoVersion = '2.4.0'
    globalTestsPowerMockitoVersion = '1.7.0RC4'
    globalTestsAssertJVersion = '3.6.2'
    globalTestJUnitParamsVersion = '1.1.0'
    globalKotlinVersion = '1.2.40'

classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${globalKotlinVersion}" // compiles Kotlin sources and modules
        classpath "de.mannodermaus.gradle.plugins:android-junit5:1.0.31"

apply plugin: 'kotlin-android' // enable Kotlin support

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).matching { "$it".contains("UnitTest") }.all {
    kotlinOptions {
        // in order to compile Kotlin to java 8 bytecode and allow to use some features of it (only for junit5 now)
        jvmTarget = "1.8"
    }
}

apply plugin: "de.mannodermaus.android-junit5" // enable junit5 tests support

dependencies {
    // kotlin
    testImplementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:${globalKotlinVersion}"
    // convenient tests libs
    testImplementation "org.mockito:mockito-core:${globalTestsMockitoVersion}"
    testImplementation "org.powermock:powermock-module-junit4:${globalTestsPowerMockitoVersion}"
    testImplementation "org.powermock:powermock-api-mockito2:${globalTestsPowerMockitoVersion}"
    testImplementation "org.assertj:assertj-core:${globalTestsAssertJVersion}"
    testImplementation "pl.pragmatists:JUnitParams:${globalTestJUnitParamsVersion}"
    // junit5 plugin (including vintage for junit 4)
    testImplementation junit5.unitTests()
    testImplementation junit5.parameterized()
}

android.testOptions {
    junitPlatform { // Configuration closure added by juni5 plugin
        jupiterVersion "5.0.3" // JUnit Jupiter dependency for junit5
        vintageVersion "4.12.2" // JUnit Vintage Engine dependency for junit4
        details "summary"
    }

    unitTests.returnDefaultValues = false // show error for non-mocked methods

    unitTests.all {
        testLogging {
            events TestLogEvent.FAILED
            outputs.upToDateWhen { false } // we want to run everytime
            showCauses true
            showExceptions true
            showStackTraces true
            exceptionFormat TestExceptionFormat.FULL
        }
    }
}

project.afterEvaluate {
    android.sourceSets.all { sourceSet ->
        if (!sourceSet.name.startsWith('test') || !sourceSet.name.startsWith('androidTest')) {
            sourceSet.kotlin.setSrcDirs([])
        }
    }
}
```
Thank you for any help or tip/clue… I will really appreciate it.

**Comment by mannodermaus** [comment]
Unfortunately, I'm unable to repro this with both AS 3.1.2 and AS 3.2.0-alpha13 and a sandbox project using version `1.0.32-SNAPSHOT` of the plugin. If possible, can you try to share an example project that exposes this problem? From a cursory glance, flaws in the JUnit 5 of Android Studio seem unrelated to the plugin, but I just want to validate that this is the case. Also, please check that using the latest snapshot version of the plugin still yields that problem after a clean rebuild!

**Comment by brainail** [comment]
Looks like it's a problem of our bulky project with really customized build steps. Wasn't able to reproduce on a simple project. 
I'm going to close it for now because I've discovered that we need `PowerMock` but **junit5-team** for now doesn't have plans to support it in several months for sure. So, for now we aren't able to use the full power of **junit5**.  
If then we drop `PowerMock` or whatever reason we are able to use junit5 I will try to use it again and if it fails with the same things then I will dive deep into this issue. 

One thing I just wanna raise that for me it was important to apply **kotlin plugin** before yours. Not sure if such detail should be mentioned somewhere in **Readme** but just wanted to let you know :) 

Thanks anyway, for now let's forget about it.

**Comment by mannodermaus** [comment]
Yeah, that's a known limitation which the plugin will address loudly with the next version, and you'll get some annoying warnings if the applied plugin order isn't correct!

Feel free to re-open this after your next experiments!
