### ISSUE TITLE
Question: How to get better stack traces on test failures with tests run from CLI?

### ISSUE THREAD

**Issue by autonomousapps** [mannodermaus/android-junit5#94]
**Issue**
Sometimes tests will fail on CLI and the output looks like this:
```
  JUnit Jupiter:AuthenticationInterceptorTest:Invalid login token error cases:intercept_POST_withLoginToken_andRequestBody_loginError_shouldReturnSuccessfulResponseEventually()
    MethodSource [className = 'com.chess.net.internal.interceptors.AuthenticationInterceptorTest$InvalidLoginTokenErrors', methodName = 'intercept_POST_withLoginToken_andRequestBody_loginError_shouldReturnSuccessfulResponseEventually', methodParameterTypes = '']
    => java.lang.NullPointerException
```
The critical line is this at the bottom:
```
    => java.lang.NullPointerException
```
But that gives no indication where the NPE was thrown.

Annoyingly, this same test invariably succeeds when run from inside Android Studio (the "big green arrow").

I was finally able to determine that the issue is a test dependency on `JSONObject`, which is actually part of the Android SDK. So the statement `new JSONObject()` actually returns null! _For some reason_, `JSONObject` and friends are actually on the classpath with tests run from inside the IDE, but are not present with tests run from the CLI (or build server, crucially). This was really hard to diagnose. (The fix was to add `testImplementation 'org.json:json:20180130'`)

**Desired outcome**
Test failures from CLI show a stacktrace. I note that passing the `--stacktrace` flag to the Gradle command just shows the following error, which is expected
```
Caused by: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/java-8-openjdk-amd64/bin/java'' finished with non-zero exit value 1
...and a lot more...
```

**Comment by mannodermaus** [comment]
You can control the level of details for logging that the JUnit Platform should perform. From the plugin's DSL, this can be controlled via:

```groovy
android {
  testOptions {
    junitPlatform {
      details "tree"
    }
  }
}
```

The available values are `[none,summary,flat,tree,verbose]`. This should give you some more insight as to what the trace behind your error is. More info can be found in the [User Guide](https://junit.org/junit5/docs/current/user-guide/#running-tests-console-launcher-options).
