### ISSUE TITLE
Switching exclude tagged tests by Build Valiants is not working

### ISSUE THREAD

**Issue by kikuchy** [mannodermaus/android-junit5#97]
# Request

Please use FiltersExtension (and TagsExtension) instances individually for each Build Valiants (tasks).

Maybe same Extension instance is used for each other tasks on version 1.0.32.
https://github.com/mannodermaus/android-junit5/blob/master/android-junit5/src/main/kotlin/de/mannodermaus/gradle/plugins/junit5/tasks/UnitTest.kt#L105 

# I want to do

I want to switch exclude tagged tests statement by Android project's Build Valiants like this.

```
    testOptions {
        unitTests.all { task ->
            if (task.name.toLowerCase().contains("debug")) {
                junitPlatform {
                    filters {
                        tags {
                            exclude 'Slow'
                        }
                    }
                }
            }
        }
    }
```

I expect excluding `@Tag("Slow")` tagged tests only at debug build (`testDebugUnitTest` task), but it excludes at release build (`testReleaseUnitTest` task) too.

**Comment by mannodermaus** [comment]
Quick update: I've released the first `1.2.0-SNAPSHOT` with support for build-variant aware filters. Please check the description on [the PR](https://github.com/mannodermaus/android-junit5/pull/100) for info on the DSL to use. Let me know if it works OK!
